.TH FUBAR 1 "NOVEMBER 2011" Linux "User Manuals"
.SH NAME
fubar \- a term-parsing calculator
.SH SYNOPSIS
.B fubar
[-i|--instant] [-q|--quiet] [--noman] [[-t|--term]
.I term
]

.B fubar
--safe [[-t|--term]
.I term
]

.B fubar
--about
.I topic

.B fubar
--help
.SH DESCRIPTION
.B fubar
is a term-parsing calculator, which supports complex numbers
and the declaration of own functions.
.SH OPTIONS
.IP "-i --instant"
Do not load 
.I autoload
file
.IP "-q --quiet"
Be quiet
.IP --noman
Disable built-in manual
.IP "-t --term"
Calculate the given term
.IP --safe
Start in safe mode
.IP --about
Output the manual text for
.I topic
.IP --help
Output a help statement.
.SH FILES
.I /etc/fubar/autoload
.RS
The global autoload file. Only used as source for recovering the local one.
.RE
.I /etc/fubar/help
.RS
The global manual file. Only used as source for recovering the local one.
.RE
.I ~/.config/fubar/autoload
.RS
Your local autoload file. Modify it to customize fubar.
.RE
.I ~/.config/fubar/help
.RS
Your local manual file.
.RE
.SH BUGS
If you find one, contact me!
.SH AUTHOR
Marvin Cohrs <implementor [at] users [dot] sourceforge [dot] net>
